### ISSUE TITLE
[Bug] Does not affect Dashboard plugin in Full Browser Window mode.

### ISSUE THREAD

**Issue by KenLucke** [jneilliii/OctoPrint-FloatingNavbar#7]
When using the Dashboard plugin in _Full Browser Window_ mode, the settings do not seem to affect it at all.  When in _Normal_ mode, or _Full Screen_ mode, it works normally.  This is the case with or without the webcam enabled.

Here are two screenshots with the settings at a ridiculously high 200 for emphasis.  The first one is in _Normal_ Mode, the second one is in _Full Browser Window_ mode. 

![Normal Mode](https://user-images.githubusercontent.com/57936294/83119633-d18c9500-a084-11ea-8933-1f860ee3383b.jpg)

![Full Browser Window Mode](https://user-images.githubusercontent.com/57936294/83119652-d8b3a300-a084-11ea-9fe8-d2e7ec5556c4.jpg)

**Comment by jneilliii** [comment]
And without this plugin installed what does it do? Please also open ticket with the dashboard plugin and link back to here, as this may be a problem on that end since full screen mode is a feature it adds.

**Comment by KenLucke** [comment]
> And without this plugin installed what does it do? Please also open ticket with the dashboard plugin and link back to here, as this may be a problem on that end since full screen mode is a feature it adds.

It works normally in all tabs except the Dashboard.  I haven't tried uninstalling Dashboard, as I'm in the middle of some multi-day prints and can't afford to restart OctoPrint and lose them.

I will see if I can open a Dashboard ticket and link back.

**Comment by jneilliii** [comment]
@KenLucke is this issue actually Themeify related maybe? I just tested Full Browser mode in the default appearance without Themeify enabled and the issue doesn't appear to be there for me.

![image](https://user-images.githubusercontent.com/5249455/83340223-7684b900-a2a3-11ea-9af2-91d72bdf46b2.png)

**Comment by KenLucke** [comment]
I thought In had disabled Themeify in my testing before filing an issue, and it made no difference, but I will check again after my printer(s) are free.

**Comment by jneilliii** [comment]
No need, I think I see what you're saying now. If I set the offset value to a high number the full browser mode is still jammed up to the top of the navbar. I'm checking into it.

**Comment by jneilliii** [comment]
Just released version 0.3.2 that resolves this issue for you @KenLucke. Let me know how it goes.

**Comment by KenLucke** [comment]
Looks good.  I lost the webcam when updating from OP, but rebooting the Pi brought it back.  Just in case others have the same issue.

thanks for your work.

**Comment by jneilliii** [comment]
Noticed an issue with the scroll to top button, so I just pushed a new version. Sorry about that.

**Comment by KenLucke** [comment]
Still having issues with the webcam showing up.  If I have two browser windows open with the same OctoPrint instance, only one of them will show the webcam.  If I refresh one browser window/tab, the webcam shows up in the other one, but it does not when the refreshed tab reloads.

github doesn't allow videos, so I have a link to a video of me doing this on dropbox:
https://www.dropbox.com/s/lbfrwkv2womwchj/screencast%202020-05-30%2020-15-49.mp4

**Comment by jneilliii** [comment]
That sounds like a dashboard plugin issue. Does it not do that when this plugin is disabled? I'm confused why my plugin would do anything to break the webcam. I do know that you have to run some internal functions in octoprint for the webcam to load and if that's not being done in the full browser mode that might cause this issue.

**Comment by KenLucke** [comment]
All I know at this point is that it didn't used to do that in the previous version I have running on the other printer.  I'll try disabling.

**Comment by KenLucke** [comment]
OK, you are correct, disabling FloatingNav Bar the problem still exists.
